version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: image-moderation-api
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
